name: Create issue from discussion and update discussion

on:
  discussion:
    types: [labeled]

jobs:
  create-issue-and-update-discussion:
    if: contains(fromJson('["explorer", "indexer"]'), github.event.label.name)
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get discussion details
        id: get_discussion
        run: |
          DISCUSSION_TITLE=$(jq -r '.discussion.title' $GITHUB_EVENT_PATH)
          DISCUSSION_BODY=$(jq -r '.discussion.body' $GITHUB_EVENT_PATH)
          DISCUSSION_URL=$(jq -r '.discussion.html_url' $GITHUB_EVENT_PATH)
          DISCUSSION_ID=$(jq -r '.discussion.node_id' $GITHUB_EVENT_PATH)
          LABEL=$(jq -r '.label.name' $GITHUB_EVENT_PATH)
          echo "title=$DISCUSSION_TITLE" >> $GITHUB_OUTPUT
          echo "body=$DISCUSSION_BODY" >> $GITHUB_OUTPUT
          echo "url=$DISCUSSION_URL" >> $GITHUB_OUTPUT
          echo "id=$DISCUSSION_ID" >> $GITHUB_OUTPUT
          echo "label=$LABEL" >> $GITHUB_OUTPUT

      - name: Create issue
        id: create_issue
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          if [ "${{ steps.get_discussion.outputs.label }}" == "explorer" ]; then
            REPO="stampchain-io/BTCStampsExplorer"
          elif [ "${{ steps.get_discussion.outputs.label }}" == "indexer" ]; then
            REPO="stampchain-io/btc_stamps"
          else
            echo "Invalid label"
            exit 1
          fi
          UNIQUE_ID="DI-$(date +%s)-$(openssl rand -hex 4)"
          ISSUE_BODY="Created from discussion: ${{ steps.get_discussion.outputs.url }}\nDiscussion-Issue-ID: $UNIQUE_ID\n\n${{ steps.get_discussion.outputs.body }}"
          RESPONSE=$(curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues \
            -d "{\"title\":\"Discussion: ${{ steps.get_discussion.outputs.title }}\", \"body\":\"$ISSUE_BODY\", \"labels\":[\"from-discussion\"]}")
          ISSUE_URL=$(echo $RESPONSE | jq -r '.html_url')
          echo "url=$ISSUE_URL" >> $GITHUB_OUTPUT
          echo "id=$UNIQUE_ID" >> $GITHUB_OUTPUT

      - name: Update discussion
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          UPDATED_BODY="${{ steps.get_discussion.outputs.body }}\n\n---\nIssue created: ${{ steps.create_issue.outputs.url }}\nDiscussion-Issue-ID: ${{ steps.create_issue.outputs.id }}"
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/graphql \
            -d "{\"query\":\"mutation { updateDiscussion(input: {discussionId: \\\"${{ steps.get_discussion.outputs.id }}\\\", body: \\\"$UPDATED_BODY\\\"}) { discussion { id } } }\"}"

      - name: Log results
        run: |
          echo "Issue created: ${{ steps.create_issue.outputs.url }}"
          echo "Discussion updated: ${{ steps.get_discussion.outputs.url }}"
          echo "Discussion-Issue-ID: ${{ steps.create_issue.outputs.id }}"