name: Add new organization discussions to project

on:
  discussion:
    types: [created, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get discussion details and add to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const fs = require('fs');
            const eventPayload = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
            console.log('Event payload:', JSON.stringify(eventPayload, null, 2));
            
            const orgLogin = eventPayload.organization.login;
            const repoName = eventPayload.repository.name;
            const discussionNumber = eventPayload.discussion.number;
            
            console.log(`Organization: ${orgLogin}, Repository: ${repoName}, Discussion Number: ${discussionNumber}`);
            
            try {
              // Fetch discussion details
              const { data: discussion } = await github.rest.discussions.get({
                owner: orgLogin,
                repo: repoName,
                discussion_number: discussionNumber
              });
              
              console.log('Discussion details:', JSON.stringify(discussion, null, 2));
              
              // Add discussion to project
              const response = await github.rest.projects.createCard({
                column_id: 'YOUR_PROJECT_COLUMN_ID',
                content_id: discussion.id,
                content_type: 'Discussion'
              });
              
              console.log('Added to project:', JSON.stringify(response.data, null, 2));
              
              return discussion.id;
            } catch (error) {
              console.error('Error:', error);
              throw error;
            }