name: Add new discussions to project

on:
  discussion:
    types: [created, reopened]

jobs:
  add-to-project:
    name: Add discussion to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Debug Info
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Discussion ID: ${{ github.event.discussion.node_id }}"
          echo "Discussion Number: ${{ github.event.discussion.number }}"
          echo "Organization: ${{ github.repository_owner }}"

      - name: Add to project
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const projectId = 'PVT_kwDOCAGLAM4Anzfw';
            const discussionId = context.payload.discussion.node_id;
            const orgName = context.payload.organization.login;
            const repoName = context.payload.repository.name;
            
            console.log(`Adding discussion ${discussionId} to project ${projectId}`);
            console.log(`Organization: ${orgName}, Repository: ${repoName}`);
            
            try {
              // First, verify the discussion exists
              const { repository } = await github.graphql(`
                query($owner: String!, $name: String!, $number: Int!) {
                  repository(owner: $owner, name: $name) {
                    discussion(number: $number) {
                      id
                      url
                    }
                  }
                }
              `, {
                owner: orgName,
                name: repoName,
                number: context.payload.discussion.number
              });
              
              if (!repository.discussion) {
                throw new Error(`Discussion not found: ${context.payload.discussion.number}`);
              }
              
              console.log(`Verified discussion ID: ${repository.discussion.id}`);
              console.log(`Discussion URL: ${repository.discussion.url}`);
              
              // Try to add it to the project using the URL
              const response = await github.graphql(`
                mutation($projectId: ID!, $url: String!) {
                  addProjectV2ItemByUrl(input: {projectId: $projectId, url: $url}) {
                    item {
                      id
                    }
                  }
                }
              `, {
                projectId: projectId,
                url: repository.discussion.url
              });
              
              console.log('Added to project:', JSON.stringify(response, null, 2));
            } catch (error) {
              console.error('Error:', error.message);
              if (error.errors) {
                error.errors.forEach((e, i) => console.error(`Error ${i + 1}:`, e));
              }
              core.setFailed(error.message);
            }