name: Add new organization discussions to project

on:
  discussion:
    types: [created, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Debug Environment
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          cat $GITHUB_EVENT_PATH

      - name: Get discussion details
        id: get_discussion
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const fs = require('fs');
            const eventPayload = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));
            console.log('Event payload:', JSON.stringify(eventPayload, null, 2));
            
            const orgLogin = eventPayload.organization?.login;
            if (!orgLogin) {
              throw new Error('Organization login not found in payload');
            }
            
            console.log('Organization login:', orgLogin);
            
            const query = `query($org: String!) {
              organization(login: $org) {
                discussionCategories(first: 10) {
                  nodes {
                    discussions(first: 1, orderBy: {field: CREATED_AT, direction: DESC}) {
                      nodes {
                        id
                        title
                        createdAt
                      }
                    }
                  }
                }
              }
            }`;
            
            const variables = { org: orgLogin };
            
            try {
              const result = await github.graphql(query, variables);
              console.log('GraphQL result:', JSON.stringify(result, null, 2));
              
              const discussions = result.organization.discussionCategories.nodes.flatMap(category => category.discussions.nodes);
              const mostRecentDiscussion = discussions.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt))[0];
              
              if (mostRecentDiscussion) {
                console.log('Most recent discussion:', JSON.stringify(mostRecentDiscussion, null, 2));
                return mostRecentDiscussion.id;
              } else {
                throw new Error('No discussions found');
              }
            } catch (error) {
              console.error('GraphQL Error:', error);
              throw error;
            }

      - name: Add to Project
        uses: actions/add-to-project@v0.6.0
        with:
          project-url: https://github.com/orgs/stampchain-io/projects/3
          github-token: ${{ steps.generate_token.outputs.token }}
          content-id: ${{ steps.get_discussion.outputs.result }}